content = File.read("Host/nks-host/main.cpp")
content.gsub!("if (module->getFactory(factory)", "std::cout << \\"Getting factory...\\\\n\\";\n    if (module->getFactory(factory)")
content.gsub!("if (factory->createInstance", "std::cout << \\"Creating instance...\\\\n\\";\n    if (factory->createInstance")
content.gsub!("if (controller) {", "std::cout << \\"Initializing controller...\\\\n\\";\n    if (controller) {")
content.gsub!("std::ifstream inFile", "std::cout << \\"Loading state...\\\\n\\";\n    std::ifstream inFile")
content.gsub!("if (component->setState", "std::cout << \\"Setting state...\\\\n\\";\n    if (component->setState")
content.gsub!("if (controller && controller->setComponentState", "std::cout << \\"Setting controller state...\\\\n\\";\n    if (controller && controller->setComponentState")
content.gsub!("component->getState", "std::cout << \\"Getting state out...\\\\n\\";\n    component->getState")
File.write("Host/nks-host/main.cpp", content)
